feat: LED with ICs
tscircuit/jlcsearch pull request #14
Opened 2024-12-24 09:15 UTC by Anshgrover23

/claim #13
Fixes #13

2024-12-24 18:08 UTC, imrishabh18 commented
LGTM!

2024-12-24 19:47 UTC, seveibar requested changes
Should have filters and more columns. Look for different interesting columns you could add. Some ideas:

- Color
- Protocol
- Number of LEDs

2024-12-26 16:52 UTC, seveibar commented
Can we do power consumption?

2024-12-28 17:39 UTC, seveibar requested changes
looks good except for api file

2024-12-28 17:39 UTC, seveibar commented on routes/led_with_ic/list.tsx
> +export default withWinterSpec({
look at the other similar files, this file is not correct for the api pattern, it should be two lines

2025-01-04 06:41 UTC, Anshgrover23 commented
@seveibar done changes.

2025-01-04 07:16 UTC, seveibar commented on routes/led_with_ic/list.tsx
> +  console.log(fullComponents)
```suggestion
```

2025-01-04 07:17 UTC, seveibar approved these changes

2025-01-04 16:41 UTC, merged